### ISSUE TITLE
frontend: list display of projects

### ISSUE THREAD

**Issue by routrohan** [MLH-Fellowship/acadivity#16]
In the "Projects" page, display the list of the projects by a user on cards. Try to integrate the timer on the same page as well.
Thanks!

**Comment by ajitesh13** [comment]
@routrohan can you send me a ss of an example design. I am not sure If I am understanding exactly of what you are expecting ?

**Comment by routrohan** [comment]
I will
But i think we should stick to a list for now
Will go for the card implementation if we get time. For now just show them all in a list with a drop down button for more info

**Comment by ajitesh13** [comment]
ok, sounds cool
