### ISSUE TITLE
Edit the issue template, error in rendering the unchecked boxes

### ISSUE THREAD

**Issue by ajitesh13** [MLH-Fellowship/acadivity#34]
## Related to frontend or backend ? 
- [] frontend
- [] backend
- [] both

## Summary
The uncheched boxes, wherever they are used are not rendering properly, add a space between them 

## Browser in which you are facing this issue ?
- [] Chrome 
- [] Firefox 
- [] Edge 
- [] Internet Explorer 

## Issue Type 

- [x] Bug 
- [] Enhancement
- [] Feature Request

**Comment by routrohan** [comment]
Hey @Ajitesh13 I can't seem to find the existing template under the feature section in Settings. Do you want me to create a new one with these specifications?
